In [1]:
import numpy as np

In [3]:
V = np.array([[23, 50],
              [7, 12]])

W = np.array([[75, 21],
              [57, 12]])

X = np.array([[57, 67],
              [99, 43]])

Y = np.array([[87, 26],
              [18, 84]])

tensor = np.array([V, W, X, Y])
tensor



array([[[23, 50],
        [ 7, 12]],

       [[75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43]],

       [[87, 26],
        [18, 84]]])

In [16]:
V.shape

(2, 2)

In [8]:
A = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])

B = np.array([[17],
              [22],
              [19]])

In [9]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [10]:
B

array([[17],
       [22],
       [19]])

In [12]:
C = A @ B

In [13]:
C

array([[1852],
       [2454],
       [4305]])

In [14]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [15]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])